import { Document, Page, View, Text, StyleSheet } from "@react-pdf/renderer";
import type { Invoice, Customer, Organization } from "@prisma/client";

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 10, fontFamily: "Helvetica", color: "#111111" },
  headerRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 24 },
  companyName: { fontSize: 16, fontWeight: 700 },
  muted: { color: "#666666" },
  title: { fontSize: 14, fontWeight: 700, marginBottom: 2 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 9, color: "#666666", marginBottom: 4, textTransform: "uppercase" },
  row: { flexDirection: "row", justifyContent: "space-between" },
  col: { flexDirection: "column" },
  table: { borderTopWidth: 1, borderColor: "#dddddd", marginTop: 8 },
  tableRow: { flexDirection: "row", borderBottomWidth: 1, borderColor: "#eeeeee", paddingVertical: 6 },
  tableHeaderRow: { flexDirection: "row", paddingVertical: 6, backgroundColor: "#f5f5f5" },
  cellMaterial: { flex: 3 },
  cell: { flex: 1, textAlign: "right" },
  totalsBlock: { marginTop: 16, alignSelf: "flex-end", width: 220 },
  totalsRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 3 },
  totalsFinalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 6,
    marginTop: 3,
    borderTopWidth: 1,
    borderColor: "#111111",
    fontWeight: 700,
  },
  footer: { position: "absolute", bottom: 24, left: 36, right: 36, fontSize: 8, color: "#999999", textAlign: "center" },
});

function fmt(n: number, currency: string) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency }).format(n);
}

export function InvoiceDocument({
  invoice,
  customer,
  organization,
}: {
  invoice: Invoice;
  customer: Customer;
  organization: Organization;
}) {
  const subtotal = Number(invoice.quantity) * Number(invoice.unitPrice);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.headerRow}>
          <View>
            <Text style={styles.companyName}>{organization.name}</Text>
            <Text style={styles.muted}>Export Invoice</Text>
          </View>
          <View style={{ alignItems: "flex-end" }}>
            <Text style={styles.title}>{invoice.invoiceNumber}</Text>
            <Text style={styles.muted}>
              {new Date(invoice.invoiceDate).toLocaleDateString("en-GB")}
            </Text>
          </View>
        </View>

        <View style={[styles.row, styles.section]}>
          <View style={styles.col}>
            <Text style={styles.sectionTitle}>Bill To</Text>
            <Text>{invoice.buyerName}</Text>
            {invoice.buyerAddress && <Text style={styles.muted}>{invoice.buyerAddress}</Text>}
            <Text style={styles.muted}>{customer.country}</Text>
          </View>
          <View style={styles.col}>
            <Text style={styles.sectionTitle}>Details</Text>
            <Text>PO Number: {invoice.poNumber ?? "—"}</Text>
            <Text>Export Country: {invoice.exportCountry}</Text>
            <Text>HSN Code: {invoice.hsnCode}</Text>
          </View>
        </View>

        <View style={styles.table}>
          <View style={styles.tableHeaderRow}>
            <Text style={styles.cellMaterial}>Material</Text>
            <Text style={styles.cell}>Qty</Text>
            <Text style={styles.cell}>Weight (kg)</Text>
            <Text style={styles.cell}>Unit Price</Text>
            <Text style={styles.cell}>Amount</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={styles.cellMaterial}>{invoice.material}</Text>
            <Text style={styles.cell}>
              {Number(invoice.quantity)} {invoice.quantityUnit}
            </Text>
            <Text style={styles.cell}>{Number(invoice.weight)}</Text>
            <Text style={styles.cell}>{fmt(Number(invoice.unitPrice), invoice.currency)}</Text>
            <Text style={styles.cell}>{fmt(subtotal, invoice.currency)}</Text>
          </View>
        </View>

        <View style={styles.totalsBlock}>
          <View style={styles.totalsRow}>
            <Text>Subtotal</Text>
            <Text>{fmt(subtotal, invoice.currency)}</Text>
          </View>
          <View style={styles.totalsRow}>
            <Text>GST ({Number(invoice.gstPercent)}%)</Text>
            <Text>{fmt(Number(invoice.gstAmount), invoice.currency)}</Text>
          </View>
          <View style={styles.totalsFinalRow}>
            <Text>Total</Text>
            <Text>{fmt(Number(invoice.totalAmount), invoice.currency)}</Text>
          </View>
        </View>

        <Text style={styles.footer}>
          Generated by ExFlow — {organization.name} · {invoice.invoiceNumber}
        </Text>
      </Page>
    </Document>
  );
}
